[package]
name = "dickfetch"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.18.0"
colored = "2.0.0"
rand = "*"
time = "*"